version: '3'
services:
  postgres:
    container_name: postgres-sql
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/posgresql/data
      POSTGRES_DB: book_social_network
    volumes:
      - ./data/postgres:/data/postgres/
    ports:
      - 5432:5432
    networks:
      - spring
  mail-dev:
    container_name: mail-dev-container
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025
    networks:
      - spring
networks:
  spring:
    driver: bridge
